@baseurl = http://localhost:3000
###
GET {{baseurl}}/api/hello

###
GET {{baseurl}}/api/error

###
GET {{baseurl}}/api/games/latest/turns/0

###
POST {{baseurl}}/api/games

###

POST {{baseurl}}/api/games/latest/turns
content-type: application/json

{
    "turnCount": 1,
    "move": {
      "disc": 1,
      "x": 3,
      "y": 3
    }
}

###

POST http://localhost:3000/api HTTP/1.1
content-type: application/json

{
    "name": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}